In [79]:
key ="2201050767bb417f928e06c7166304c6b41e485d"
b_key ="641DEDB0-361B-441D-BF2E-215378D97EB4"
from census import Census
from us import states
%matplotlib inline
import seaborn as sns
import matplotlib

import matplotlib.pyplot as plt
import numpy as np
import requests
import pandas as pd
pd.options.mode.chained_assignment = None 
import os
import requests
import urllib.request, json 
import pybea
from scipy.stats import norm
from matplotlib.ticker import PercentFormatter
matplotlib.style.use('ggplot')


def get_perc(times,total,df):
    portions = []
    for i in times:
        portions.append(100 * df[i].sum()/df[total].sum())
    return portions


c = Census(key)

In [80]:
x = c.acs5.get(('NAME', 'B01003_001E','B05002_013E','B05002_013M','B01002_001E','B01002_001M',
                'B03002_003E','B03002_004E','B03002_005E','B03002_006E','B03002_009E',
                'B03002_007E','B03002_008E','B06012_002E','B05010_001E','B19013_001E','B08303_001E',
                'B08303_002E','B03002_012E',
               'B08303_003E','B08303_004E','B08303_005E','B08303_006E','B08303_007E','B08303_008E',
               'B08303_009E','B08303_010E','B08303_011E','B08303_012E','B08303_013E',
                'B06009_001E','B06009_002E','B06009_003E','B06009_004E','B06009_005E','B06009_006E',
                "B19013_001E",
                "B01001_003E","B01001_004E","B01001_005E","B01001_006E","B01001_027E"
                ,"B01001_028E","B01001_029E","B01001_030E","B17012_019E","B08131_001E","B23025_005E",
                "B23025_002E"
                
               ),
          {'for': '{}'.format("county")})

In [81]:
counties = pd.read_table("https://www2.census.gov/geo/docs/reference/codes/files/national_county.txt", sep = ",",
                        names = ["State","SFip","CFIP","County Name", "H"],header = None)

In [82]:
counties.head()
counties["geo_id"] =counties["SFip"].astype(str).str.zfill(2) +counties["CFIP"].astype(str).str.zfill(3) 
counties.head()

  State  SFip  CFIP     County Name   H geo_id
0    AL     1     1  Autauga County  H1  01001
1    AL     1     3  Baldwin County  H1  01003
2    AL     1     5  Barbour County  H1  01005
3    AL     1     7     Bibb County  H1  01007
4    AL     1     9   Blount County  H1  01009

In [63]:
metros = pd.read_csv("metro_size.csv")

In [64]:
counties["County Name"]

In [65]:
metros["County Name"].head()

0    Autauga County
1    Baldwin County
2    Barbour County
3       Bibb County
4     Blount County
Name: County Name, dtype: object

In [67]:
new_df =pd.DataFrame(x)
new_df = new_df.rename(columns={"NAME":'County Name'})
new_df.head()

,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01002_001E,B01002_001M,...,B08303_011E,B08303_012E,B08303_013E,B17012_019E,B19013_001E,B23025_002E,B23025_005E,County Name,county,state
0,1680.0,2003.0,2112.0,1327.0,1492.0,1816.0,2127.0,1296.0,37.8,0.5,...,1383.0,719.0,544.0,13273.0,53099.0,26008.0,1437.0,"Autauga County, Alabama",001,01
1,5876.0,6197.0,6399.0,4106.0,5556.0,6316.0,6175.0,3645.0,42.3,0.3,...,8729.0,4957.0,1841.0,45500.0,51365.0,93872.0,5887.0,"Baldwin County, Alabama",003,01
2,740.0,875.0,812.0,516.0,732.0,838.0,777.0,445.0,38.7,0.6,...,725.0,408.0,229.0,4777.0,33956.0,10316.0,1323.0,"Barbour County, Alabama",005,01
3,471.0,643.0,812.0,569.0,679.0,542.0,695.0,345.0,40.2,0.9,...,1440.0,513.0,104.0,4654.0,39776.0,9002.0,643.0,"Bibb County, Alabama",007,01
4,1818.0,1644.0,2211.0,1230.0,1694.0,2136.0,1702.0,1166.0,40.8,0.4,...,4346.0,2911.0,649.0,13559.0,46212.0,22969.0,1367.0,"Blount County, Alabama",009,01

In [72]:
county_count = pd.merge(metros,counties,on ="County Name",how = "outer",indicator = True)

In [73]:
county_count.head()

,County Name,State_x,Metro Code,OMB County Status,Total Population (civilian non-institutionalized),Total Population (Margin of Error),Disability Population (civilian non-institutionalized),Disability Population (Margin of Error),Percent with a Disability,Gender- Male Disability Rate- Percentage of males reporting a disability,...,Disability Unemployment Rates- Percentage of individuals with a reported disability unemployed in the labor force,Out of the Labor Force Disability Rate- Percentage of individuals with a reported disability not in the labor force,Veteran Disability Rate- Percentage of veterans reporting a disability,Disability Poverty Rate- Percentage of individuals reporting a disability in poverty,State_y,SFip,CFIP,H,geo_id,_merge
0,Autauga County,Alabama,1.0,Metropolitan,54425.0,239.0,9400.0,690.0,17.3,17.5,...,7.9,57.0,28,25.2,AL,1.0,1.0,H1,01001,both
1,Baldwin County,Alabama,1.0,Metropolitan,192770.0,369.0,26550.0,1256.0,13.8,14.0,...,7.3,63.0,30.1,17.6,AL,1.0,3.0,H1,01003,both
2,Baldwin County,Alabama,1.0,Metropolitan,192770.0,369.0,26550.0,1256.0,13.8,14.0,...,7.3,63.0,30.1,17.6,GA,13.0,9.0,H1,13009,both
3,Baldwin County,Georgia,2.0,Micropolitan,43526.0,389.0,5636.0,493.0,12.9,13.2,...,2.1,76.1,25,27.8,AL,1.0,3.0,H1,01003,both
4,Baldwin County,Georgia,2.0,Micropolitan,43526.0,389.0,5636.0,493.0,12.9,13.2,...,2.1,76.1,25,27.8,GA,13.0,9.0,H1,13009,both

In [77]:
right = county_count[county_count["_merge"] == "right_only"]

In [78]:
right.head()

,County Name,State_x,Metro Code,OMB County Status,Total Population (civilian non-institutionalized),Total Population (Margin of Error),Disability Population (civilian non-institutionalized),Disability Population (Margin of Error),Percent with a Disability,Gender- Male Disability Rate- Percentage of males reporting a disability,...,Disability Unemployment Rates- Percentage of individuals with a reported disability unemployed in the labor force,Out of the Labor Force Disability Rate- Percentage of individuals with a reported disability not in the labor force,Veteran Disability Rate- Percentage of veterans reporting a disability,Disability Poverty Rate- Percentage of individuals reporting a disability in poverty,State_y,SFip,CFIP,H,geo_id,_merge
14569,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,AK,2.0,13.0,H1,02013,right_only
14570,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,AK,2.0,16.0,H5,02016,right_only
14571,Anchorage Municipality,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,AK,2.0,20.0,H6,02020,right_only
14572,Bethel Census Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,AK,2.0,50.0,H5,02050,right_only
14573,Bristol Bay Borough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,AK,2.0,60.0,H1,02060,right_only

In [83]:
len(counties)

3235

In [85]:
len(new_df)

3220

In [103]:
areas = pd.read_excel("list1.xls")
areas.head()

,Table with row headers in column A and column headers in row 3,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"List 1. CORE BASED STATISTICAL AREAS (CBSAs), ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
2,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46,013,Central
3,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46,045,Outlying
4,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53,027,Central

In [104]:
areas.columns = areas.iloc[1]
areas.head()

1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,"List 1. CORE BASED STATISTICAL AREAS (CBSAs), ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
2,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46,013,Central
3,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46,045,Outlying
4,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53,027,Central

In [105]:
areas.index.drop(1)
areas.head()

1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,"List 1. CORE BASED STATISTICAL AREAS (CBSAs), ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
2,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46,013,Central
3,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46,045,Outlying
4,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53,027,Central

In [106]:
areas = areas.drop(areas.index[0])
areas = areas.drop(areas.index[0])
areas.head()

1,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
2,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46,013,Central
3,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46,045,Outlying
4,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53,027,Central
5,10180,NaN,NaN,"Abilene, TX",Metropolitan Statistical Area,NaN,NaN,Callahan County,Texas,48,059,Outlying
6,10180,NaN,NaN,"Abilene, TX",Metropolitan Statistical Area,NaN,NaN,Jones County,Texas,48,253,Outlying

In [107]:
areas["geo_id"] = areas["CBSA Code"]

In [108]:
county_count = pd.merge(areas,counties,on ="geo_id")

In [109]:
len(county_count)

0

In [110]:
counties["geo_id"]

0       01001
1       01003
2       01005
3       01007
4       01009
5       01011
6       01013
7       01015
8       01017
9       01019
10      01021
11      01023
12      01025
13      01027
14      01029
15      01031
16      01033
17      01035
18      01037
19      01039
20      01041
21      01043
22      01045
23      01047
24      01049
25      01051
26      01053
27      01055
28      01057
29      01059
        ...
3205    72103
3206    72105
3207    72107
3208    72109
3209    72111
3210    72113
3211    72115
3212    72117
3213    72119
3214    72121
3215    72123
3216    72125
3217    72127
3218    72129
3219    72131
3220    72133
3221    72135
3222    72137
3223    72139
3224    72141
3225    72143
3226    72145
3227    72147
3228    72149
3229    72151
3230    72153
3231    74300
3232    78010
3233    78020
3234    78030
Name: geo_id, Length: 3235, dtype: object